spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/leaguacy
    username: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
