spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/leaguacy
    username:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
