version: "3.9"
services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql_leaguacy
    ports:
      - 3306:3306
    volumes:
      - ../../mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=leaguacy
