version: "3.9"
services:
  mysql:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ../../postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
